# Generated by Django 3.2.25 on 2025-02-27 11:41

import createassoc.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code_Koraa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(default=createassoc.models.generate_hex_code, editable=False, max_length=16, unique=True)),
                ('amount', models.IntegerField()),
                ('number_part', models.IntegerField()),
                ('date_deb', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code_koraa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='createassoc.code_koraa')),
            ],
        ),
    ]
