# Generated by Django 3.2.25 on 2025-03-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createassoc', '0002_participant_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
